### ISSUE TITLE
How to calculate the parameter in constraints file like example.con.txt

### ISSUE THREAD

**Issue by Yung-Chien** [mmatschiner/snapp_prep#2]
Hello @mmatschiner ,
I'm confused about the constraints file's parameter when I would like to generate a input file of SNAPP,so how could I calculate these parameters and could I get them in the SNP or phylip
file? Or does this file have a default value?

Best regards,
Yung-Chien

**Comment by mmatschiner** [comment]
Hi Yung-Chien,
no, this file does not have default values. If you want to time-calibrate your phylogeny with this approach in SNAPP (or any other node-dating approach) you'll need to have some external information about the ages of one or more nodes of the phylogeny. If for example another study has dated a node that is also included in your phylogeny to 10 Ma and a 95% confidence interval from 9-11 Ma, you could use a normal distribution with a mean of 10 and a standard deviation adjusted so that 95% of the distribution lies within 9-11, to constrain the age of that node in your phylogeny (assuming that the other study estimated that age correctly).
But I recommend checking the BEAST2 book by Alexei Drummond and Remco Bouckaert ("Bayesian evolutionary analysis with BEAST 2") to learn more about how you built priors according to your expectations for certain node ages.
Best regards,
Michael
